Repository josephaw1022/InternshipJavaApp, pull requests merged in 2021-10, with the labels that each got.

#5 Student
  ApplicationManager.java
  Student.java
Labels: Review Me

#10 Application UI class
  applicationUI.java
Labels: Review Me

#24 Update README.md
  README.md
Labels: Refix

#22 added src package declaration, fixed type errors
  src/Admin.java
  src/ApplicationManager.java
  src/Company.java
  src/Employee.java
  src/EndpointCompany.java
  src/EndpointJob.java
  src/EndpointUser.java
  src/JobListing.java
  src/Resume.java
  src/ResumeExperience.java
  src/Review.java
  src/Student.java
  src/User.java
  src/applicationUI.java
  src/data/resumes.json
  src/data/students.json
  src/data/users.json
Labels: In-Progress (Changes Requested)

#28 Create LICENSE
  LICENSE
Labels: Enhancement, Closed (Merged)

#29 printing uuids for json and changing json structure
  src/ApplicationUI.java
  src/UUIDPrint.java
  src/data/students.json
Labels: Closed (Merged)

#34 Endpoint CRUD Methods
  src/EndpointCompany.java
  src/EndpointJob.java
  src/EndpointUser.java
Labels: Enhancement, Awaiting Review
